In [0]:
import numpy as np
import tensorflow as tf

%matplotlib inline

# Con el fin de poder comparar los resultados
np.random.seed(2)

In [3]:
y_hat = tf.constant(25, name = 'y_hat') #Definir una constante y_hat = 25
y = tf.constant(29, name = 'y')  #Definir una constante y = 29
loss = (y-y_hat)**2     #Definir una variable y asignar (y-y_hat)**2
init = tf.global_variables_initializer()  #Definir la inicialización de variables
session = tf.Session()   #Crear una sesión e imprimir la salida
session.run(init)        #Ejecutar la inicializión de las variables
r = session.run(loss)    #Ejecutar el cálculo de loss
print(f"loss = {r}")                  

loss = 16


In [4]:
a = tf.constant(2, name = 'a')
b = tf.constant(10, name = 'b')
c =  tf.multiply(a , b)
print(f"c = {c}")
session = tf.Session()
print(f"c = {session.run(c)}")

c = Tensor("Mul:0", shape=(), dtype=int32)
c = 20


In [5]:
z = tf.placeholder(tf.int32, name='z')
r = session.run(3*z, feed_dict = {z: 3})
print(f"r = {r}")
session.close()

r = 9


In [6]:
def linear_function():
    np.random.seed(1)
    
    #Inicialice las constantes X, W, b
    X = tf.constant(np.random.randn(3,1), name = "X")
    W = tf.constant(np.random.randn(4,3), name = "W")
    b = tf.constant(np.random.randn(4,1), name = "b")

    #Defina las operaciones del grafo de cómputo
    Y = tf.add(tf.matmul(W, X), b)
    
    #Crear la sesión y ejecutarla
    session = tf.Session()
    result = session.run(Y)
    session.close()
    
    return result

print(f"result = {linear_function()}")

result = [[-2.15657382]
 [ 2.95891446]
 [-1.08926781]
 [-0.84538042]]


In [9]:
def sigmoid(z):
    # Crear el placeholder para x, nombrarla x
    x = tf.placeholder(tf.float32, name='x')

    # Definir el cálculo de la sigmoidal
    sigmoid = tf.sigmoid(x)
    
    session = tf.Session()
    result = session.run(sigmoid, feed_dict = {x: z})
    
    return result

print(f"sigmoid(0) = {sigmoid(0)}")
print(f"sigmoid(12) = {sigmoid(12)}")

sigmoid(0) = 0.5
sigmoid(12) = 0.9999938011169434


In [12]:
def cost(logits, labels):
    """
    Parámetros:
    
    logits  vector que contiene las entradas a la unidad de activación (antes de la activación sigmoidal final)
    labels  vector de etiquetas (1 o 0)
    """
    
    #Crear los placeholders para Z y las etiquetas
    z = tf.placeholder(tf.float32, name='z')
    y = tf.placeholder(tf.float32, name='y')
    
    # Utilice la función de costo
    cost = tf.nn.sigmoid_cross_entropy_with_logits(logits = z, labels = y)
    
    #crear una sesión
    session =  tf.Session()
    
    #Ejecutar la sesión
    cost = session.run(cost,feed_dict = {z: logits, y : labels})
    
    #Cerrar la sesión
    session.close()
    
    return cost

logits = sigmoid(np.array([0.2,0.4,0.7,0.9]))
cost = cost(logits, np.array([0,0,1,1]))
print (f"cost = {cost}")

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
cost = [1.0053872  1.0366409  0.41385433 0.39956614]


In [16]:
def one_hot_encoding(label, C):
    C = tf.constant(C, name='C')
    
    one_hot_encode = tf.one_hot(labels, C, axis=0)
    
    session = tf.Session()
    one_hot = session.run(one_hot_encode)
    session.close()
    
    return one_hot

labels = np.array([1,2,0,2,1,0])
one_hot = one_hot_encoding(labels, C = 3)
print (f"{one_hot}")

[[0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0. 0.]]


In [17]:
def ones(shape):
    
    ones = tf.ones(shape)
    
    session = tf.Session()
    
    ones = session.run(ones)
    session.close()
    
    return ones

print (f"{ones([3])}")

[1. 1. 1.]
